name: Deploy Text-to-Video Generator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install FFmpeg and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libsm6 libxext6

    - name: Clone LTX Video repository
      run: git clone https://huggingface.co/spaces/Jaan22/ltx-video-distilled

    - name: Install Python dependencies
      working-directory: ./ltx-video-distilled
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test the application
      working-directory: ./ltx-video-distilled
      run: |
        python -c "
import os
print('Testing LTX Video application...')
print('Current directory:', os.getcwd())
print('Files in directory:', os.listdir('.'))
try:
    with open('app.py', 'r') as f:
        print('app.py exists and can be read')
    print('✓ Application ready to run')
except Exception as e:
    print('✗ Error:', e)
        "

    - name: Run the text-to-video application
      working-directory: ./ltx-video-distilled
      run: |
        echo "Starting LTX Video text-to-video generator..."
        python app.py
