name: Simple Clone and Run

on:
  push:
    branches: [ main ]

jobs:
  simple:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone and setup Jaan22 LTX Video
      run: |
        git clone https://huggingface.co/spaces/Jaan22/ltx-video-distilled
        cd ltx-video-distilled
        pip install -r requirements.txt
        python -c "print('LTX Video setup completed!')"
