name: Deploy Text-to-Video App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Clone and setup
      run: |
        git clone https://huggingface.co/spaces/Jaan22/ltx-video-distilled
        cd ltx-video-distilled
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test installation
      working-directory: ./ltx-video-distilled
      run: |
        source env/bin/activate
        python -c "import gradio; print('Gradio installed successfully')"
