name: Run Text-to-Video Generator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Clone repository
      run: git clone https://huggingface.co/spaces/Jaan22/ltx-video-distilled

    - name: Install dependencies
      working-directory: ./ltx-video-distilled
      run: |
        pip install -r requirements.txt

    - name: Run text-to-video application
      working-directory: ./ltx-video-distilled
      run: |
        python app.py
